"""
motif.py
---------
Section 13: conserved motif discovery within CDR1/CDR2/CDR3.

Recommended approach for a reference-free VHH repertoire:
1. Group CDR sequences by length (motifs are only meaningfully "aligned"
   within a length group; see cdr_length_analysis.py) -- this itself is
   already a big part of "motif discovery" for junctional CDR3s.
2. Within each length group, compute per-position amino-acid frequencies
   (diversity.position_specific_variability) and render as a sequence logo
   (plotting.plot_sequence_logo) -- conserved positions show low entropy /
   a dominant residue.
3. For motifs that may occur at variable positions/lengths (e.g. a short
   conserved sub-motif embedded in an otherwise variable CDR3), use
   ungapped k-mer enrichment: count all k-mers (k=3-5) across all CDR3s of
   any length and compare their frequency to a shuffled/null background --
   this is analogous to classic motif-enrichment tools (e.g. MEME's
   philosophy) but implemented simply here for speed and dependency-freeness.
   For rigorous statistical motif discovery, MEME Suite / STREME (via the
   `meme` command-line tools) or `pyMEME` bindings are recommended as an
   external validation step, not reimplemented here.
"""
from __future__ import annotations

import logging
from collections import Counter
from itertools import product

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


def kmer_enrichment(sequences: list[str], k: int = 3, n_shuffles: int = 100,
                     random_state: int = 42) -> pd.DataFrame:
    """
    Compare observed k-mer frequencies in `sequences` to a null distribution
    generated by shuffling residues within each sequence (preserves per-
    sequence amino-acid composition and length, destroys positional/motif
    structure). Returns k-mers sorted by enrichment (observed / mean(null)).
    """
    rng = np.random.default_rng(random_state)

    def count_kmers(seqs):
        counts = Counter()
        for s in seqs:
            for i in range(len(s) - k + 1):
                counts[s[i:i + k]] += 1
        return counts

    observed = count_kmers(sequences)

    null_counts = Counter()
    for _ in range(n_shuffles):
        shuffled = ["".join(rng.permutation(list(s))) for s in sequences]
        for kmer, c in count_kmers(shuffled).items():
            null_counts[kmer] += c

    rows = []
    for kmer, obs_count in observed.items():
        null_mean = null_counts.get(kmer, 0) / n_shuffles
        enrichment = obs_count / null_mean if null_mean > 0 else np.inf
        rows.append({"kmer": kmer, "observed_count": obs_count, "null_mean_count": null_mean,
                     "enrichment": enrichment})
    df = pd.DataFrame(rows).sort_values("enrichment", ascending=False).reset_index(drop=True)
    logger.info("k-mer enrichment (k=%d): top hit %s (enrichment=%.2f)",
                k, df.iloc[0]["kmer"] if len(df) else None, df.iloc[0]["enrichment"] if len(df) else float("nan"))
    return df


def conserved_positions(pos_variability_df: pd.DataFrame, entropy_threshold: float = 0.3) -> pd.DataFrame:
    """Flag low-entropy (highly conserved) positions from position_specific_variability output."""
    out = pos_variability_df.copy()
    out["is_conserved"] = out["entropy"] <= entropy_threshold
    return out
